USE Karify;
GO
IF EXISTS (SELECT * FROM sys.procedures WHERE name = 'usp_ObtenerInformacionPersonal') 
	BEGIN
		DROP PROCEDURE usp_ObtenerInformacionPersonal;
	END
GO

CREATE PROCEDURE usp_ObtenerInformacionPersonal
(
	@pIdUsuario INT
)
AS
BEGIN
	(SELECT 
		USU.Id AS [ID],
		USU.CodigoUniversitario AS [CODIGO_UNIVERSITARIO],
		ALUM.TipoDocumento AS [TIPO_DOCUMENTO],
		ALUM.NumeroDocumento AS [NUMERO_DOCUMENTO],
		ALUM.Nombre AS [NOMBRE],
		ALUM.ApellidoPaterno AS [APELLIDO_PATERNO],
		ALUM.ApellidoMaterno AS [APELLIDO_MATERNO],
		USU.Correo AS [CORREO],
		ALUM.Telefono AS [TELEFONO],
		FACU.Id AS [ID_FACULTAD],
		ESCU.Id AS [ID_ESCUELA]
	FROM USUARIO USU
	INNER JOIN ALUMNO ALUM ON ALUM.IdUsuario = USU.Id
	LEFT JOIN ESCUELA ESCU ON ESCU.Id = USU.IdEscuela
	LEFT JOIN FACULTAD FACU ON FACU.Id = ESCU.IdFacultad
	WHERE USU.Id = @pIdUsuario)
	UNION ALL 
	(SELECT 
		USU.Id AS [ID],
		USU.CodigoUniversitario AS [CODIGO_UNIVERSITARIO],
		PRO.TipoDocumento AS [TIPO_DOCUMENTO],
		PRO.NumeroDocumento AS [NUMERO_DOCUMENTO],
		PRO.Nombre AS [NOMBRE],
		PRO.ApellidoPaterno AS [APELLIDO_PATERNO],
		PRO.ApellidoMaterno AS [APELLIDO_MATERNO],
		USU.Correo AS [CORREO],
		PRO.Telefono AS [TELEFONO],
		FACU.Id AS [ID_FACULTAD],
		ESCU.Id AS [ID_ESCUELA]
	FROM USUARIO USU
	INNER JOIN PROFESOR PRO ON PRO.IdUsuario = USU.Id
	LEFT JOIN ESCUELA ESCU ON ESCU.Id = USU.IdEscuela
	LEFT JOIN FACULTAD FACU ON FACU.Id = ESCU.IdFacultad
	WHERE USU.Id = @pIdUsuario)

END