USE Karify;
GO
IF EXISTS (SELECT * FROM sys.procedures WHERE name = 'usp_VerProyecto') 
	BEGIN
		DROP PROCEDURE usp_VerProyecto;
	END
GO

CREATE PROCEDURE usp_VerProyecto
(
	@pIdProyecto INT
)
AS
BEGIN
	
	SELECT
		PRO.Id AS [ID],
		PRO.Nombre AS [NOMBRE],
		PRO.Descripcion AS [DESCRIPCION],
		PRO.IdProfesor AS [PROFESOR],
		CONCAT(PROF.Nombre, ' ', 
			PROF.ApellidoPaterno, ' ', 
			PROF.ApellidoMaterno) AS [NOMBRE_PROFESOR],
		ALU.Id AS [COTESISTA],
		CONCAT(ALU.Nombre, ' ', 
			ALU.ApellidoPaterno, ' ', 
			ALU.ApellidoMaterno) AS [NOMBRE_COTESISTA],
		PRO.FechaRegistro AS [FECHA_REGISTRO],
		REV.ArchivoBase64 AS [ARCHIVO],
		REV.NombreArchivo AS [NOMBRE_ARCHIVO],
		REV.Estado AS [ESTADO],
		(CASE
			WHEN PROXALU.IsPrincipal = 0
			THEN 1 ELSE 0 END) AS [ES_COTESISTA]
	FROM PROYECTO PRO
	INNER JOIN PROYECTOXALUMNO PROXALU ON PROXALU.IdProyecto = PRO.Id
	LEFT JOIN PROYECTOXALUMNO PROXALU2 ON PROXALU2.IdProyecto = PRO.Id
	LEFT JOIN ALUMNO ALU ON ALU.Id = PROXALU2.IdAlumno
	LEFT JOIN PROFESOR PROF ON PROF.Id = PRO.IdProfesor
	LEFT JOIN REVISION REV ON REV.IdProyecto = PRO.Id
	WHERE PRO.Id = @pIdProyecto

END